# Best articles
# https://bitbucket.org/blog/automate-publishing-your-android-application-with-bitbucket-pipelines-and-gradle
# https://github.com/Triple-T/gradle-play-publisher
# https://medium.com/nerd-for-tech/ci-cd-for-android-using-bitbucket-pipelines-and-gradle-play-publisher-f00d6047ecb5

image: androidsdk/android-30

pipelines:
  branches:
    master:
      - step:
          name: Create keystore and API key
          script:
            # create the keystore file and the google play api key file
            - mkdir keys
            - echo $ONEGRAVITY_KEYSTORE_FILE_BASE64 | base64 --decode > keys/$ONEGRAVITY_KEYSTORE_FILE
            - echo $ONEGRAVITY_GOOGLE_PLAY_API_KEY_BASE64 | base64 --decode > keys/$ONEGRAVITY_GOOGLE_PLAY_API_KEY
          artifacts:
            - keys/**
      - parallel:
          - step:
              name: Run code analysis
              size: 2x
              caches:
                - gradle
              script:
                - JAVA_OPTS="-Xmx4096m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
                - export GRADLE_OPTS='-XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=2048m -XX:ReservedCodeCacheSize=440m -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true'
                - "./gradlew -PONEGRAVITY_KEYSTORE_FILE=../keys/$ONEGRAVITY_KEYSTORE_FILE
                             -PONEGRAVITY_KEYSTORE_PASSWORD=$ONEGRAVITY_KEYSTORE_PASSWORD
                             -PONEGRAVITY_SUDOKU10k_KEY_ALIAS=$ONEGRAVITY_TICHUSCORE_KEY_ALIAS
                             -PONEGRAVITY_SUDOKU10k_KEY_PASSWORD=$ONEGRAVITY_TICHUSCORE_KEY_PASSWORD
                             -PONEGRAVITY_GOOGLE_PLAY_API_KEY=../keys/$ONEGRAVITY_GOOGLE_PLAY_API_KEY
                             lint"
              artifacts:
                - tichu-score/build/outputs/**
                - tichu-score/build/reports/**
          - step:
              name: Run unit tests
              caches:
                - gradle
              script:
                - export GRADLE_OPTS='-XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=440m -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true'
                - "./gradlew -PONEGRAVITY_KEYSTORE_FILE=../keys/$ONEGRAVITY_KEYSTORE_FILE
                             -PONEGRAVITY_KEYSTORE_PASSWORD=$ONEGRAVITY_KEYSTORE_PASSWORD
                             -PONEGRAVITY_SUDOKU10k_KEY_ALIAS=$ONEGRAVITY_TICHUSCORE_KEY_ALIAS
                             -PONEGRAVITY_SUDOKU10k_KEY_PASSWORD=$ONEGRAVITY_TICHUSCORE_KEY_PASSWORD
                             -PONEGRAVITY_GOOGLE_PLAY_API_KEY=../keys/$ONEGRAVITY_GOOGLE_PLAY_API_KEY
                             test"
              artifacts:
                - tichu-score/build/outputs/**
                - tichu-score/build/reports/**
          - step:
              name: Build & deploy
              caches:
                - gradle
              script:
                # publish the aab file to the internal testing channel
                - export GRADLE_OPTS='-XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=440m -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true'
                - "./gradlew -PONEGRAVITY_KEYSTORE_FILE=../keys/$ONEGRAVITY_KEYSTORE_FILE
                             -PONEGRAVITY_KEYSTORE_PASSWORD=$ONEGRAVITY_KEYSTORE_PASSWORD
                             -PONEGRAVITY_SUDOKU10k_KEY_ALIAS=$ONEGRAVITY_TICHUSCORE_KEY_ALIAS
                             -PONEGRAVITY_SUDOKU10k_KEY_PASSWORD=$ONEGRAVITY_TICHUSCORE_KEY_PASSWORD
                             -PONEGRAVITY_GOOGLE_PLAY_API_KEY=../keys/$ONEGRAVITY_GOOGLE_PLAY_API_KEY
                             -PBUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                             clean :tichu-score:publishReleaseBundle --stacktrace"
              artifacts:
                - sudoku-10k/build/outputs/
          - step:
              name: Promote
              trigger: manual
              caches:
                - gradle
              script:
                # promote the app from the internal testing channel to the production channel
                - export GRADLE_OPTS='-XX:+UseG1GC -XX:MaxGCPauseMillis=1000 -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=440m -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" -Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true'
                - "./gradlew -PONEGRAVITY_KEYSTORE_FILE=../keys/$ONEGRAVITY_KEYSTORE_FILE
                             -PONEGRAVITY_KEYSTORE_PASSWORD=$ONEGRAVITY_KEYSTORE_PASSWORD
                             -PONEGRAVITY_SUDOKU10k_KEY_ALIAS=$ONEGRAVITY_TICHUSCORE_KEY_ALIAS
                             -PONEGRAVITY_SUDOKU10k_KEY_PASSWORD=$ONEGRAVITY_TICHUSCORE_KEY_PASSWORD
                             -PONEGRAVITY_GOOGLE_PLAY_API_KEY=../keys/$ONEGRAVITY_GOOGLE_PLAY_API_KEY
                             -PBUILD_NUMBER=$BITBUCKET_BUILD_NUMBER
                              promoteReleaseArtifact --from-track internal --promote-track production --release-status completed"
