# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :tests do
    gradle(task: "testProductionReleaseUnitTest")
  end

  desc "Build a new production version (signed)"
  lane :build do
    gradle(task: "clean")
    gradle(
      task: 'bundleProduction',
      build_type: 'Release'
    )
  end

  desc "Build and deploy a new production version to the internal testing track"
  lane :playstore do
    tests
    build
    upload_to_play_store(track: 'internal')
  end

end
